# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fv2twM49fWydEBfCr9fm6Ms54hRb3TUJ
"""

import torch
import torch.nn as nn
import torch.optim as optim
import torchvision
import torchvision.transforms as transforms
import matplotlib.pyplot as plt
import numpy as np
import os

torch.manual_seed(42)
np.random.seed(42)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")


class PrunableLinear(nn.Module):
    def __init__(self, in_features, out_features):
        super().__init__()
        self.weight = nn.Parameter(torch.empty(out_features, in_features))
        self.bias = nn.Parameter(torch.zeros(out_features))
        self.gate_scores = nn.Parameter(torch.zeros(out_features, in_features))
        nn.init.kaiming_uniform_(self.weight, a=np.sqrt(5))

    def forward(self, x):
        gates = torch.sigmoid(self.gate_scores)
        pruned_weights = self.weight * gates
        return nn.functional.linear(x, pruned_weights, self.bias)

    def get_gates(self):
        return torch.sigmoid(self.gate_scores).detach()


class SelfPruningNet(nn.Module):
    def __init__(self):
        super().__init__()

        self.features = nn.Sequential(
            nn.Conv2d(3, 64, kernel_size=3, padding=1),
            nn.BatchNorm2d(64),
            nn.ReLU(inplace=True),
            nn.Conv2d(64, 64, kernel_size=3, padding=1),
            nn.BatchNorm2d(64),
            nn.ReLU(inplace=True),
            nn.MaxPool2d(2, 2),
            nn.Dropout2d(0.1),

            nn.Conv2d(64, 128, kernel_size=3, padding=1),
            nn.BatchNorm2d(128),
            nn.ReLU(inplace=True),
            nn.Conv2d(128, 128, kernel_size=3, padding=1),
            nn.BatchNorm2d(128),
            nn.ReLU(inplace=True),
            nn.MaxPool2d(2, 2),
            nn.Dropout2d(0.2),

            nn.Conv2d(128, 256, kernel_size=3, padding=1),
            nn.BatchNorm2d(256),
            nn.ReLU(inplace=True),
            nn.Conv2d(256, 256, kernel_size=3, padding=1),
            nn.BatchNorm2d(256),
            nn.ReLU(inplace=True),
            nn.MaxPool2d(2, 2),
            nn.Dropout2d(0.3),
        )

        self.flatten = nn.Flatten()

        self.fc1 = PrunableLinear(256 * 4 * 4, 1024)
        self.bn1 = nn.BatchNorm1d(1024)
        self.drop1 = nn.Dropout(0.4)

        self.fc2 = PrunableLinear(1024, 512)
        self.bn2 = nn.BatchNorm1d(512)
        self.drop2 = nn.Dropout(0.4)

        self.fc3 = PrunableLinear(512, 10)

        self.relu = nn.ReLU(inplace=True)

    def forward(self, x):
        x = self.features(x)
        x = self.flatten(x)
        x = self.drop1(self.relu(self.bn1(self.fc1(x))))
        x = self.drop2(self.relu(self.bn2(self.fc2(x))))
        return self.fc3(x)

    def sparsity_loss(self):
        total = torch.tensor(0.0, device=device)
        for module in self.modules():
            if isinstance(module, PrunableLinear):
                total = total + torch.sigmoid(module.gate_scores).sum()
        return total

    def get_all_gates(self):
        all_gates = []
        for module in self.modules():
            if isinstance(module, PrunableLinear):
                all_gates.append(module.get_gates().cpu().numpy().flatten())
        return np.concatenate(all_gates)

    def compute_sparsity(self, threshold=1e-2):
        gates = self.get_all_gates()
        return 100.0 * np.sum(gates < threshold) / len(gates)


def get_cifar10_loaders(batch_size=128):
    train_transform = transforms.Compose([
        transforms.RandomHorizontalFlip(),
        transforms.RandomCrop(32, padding=4),
        transforms.ColorJitter(brightness=0.2, contrast=0.2, saturation=0.2),
        transforms.RandomRotation(10),
        transforms.ToTensor(),
        transforms.Normalize((0.4914, 0.4822, 0.4465), (0.2023, 0.1994, 0.2010)),
    ])
    test_transform = transforms.Compose([
        transforms.ToTensor(),
        transforms.Normalize((0.4914, 0.4822, 0.4465), (0.2023, 0.1994, 0.2010)),
    ])
    train_set = torchvision.datasets.CIFAR10(root="./data", train=True, download=True, transform=train_transform)
    test_set = torchvision.datasets.CIFAR10(root="./data", train=False, download=True, transform=test_transform)
    train_loader = torch.utils.data.DataLoader(train_set, batch_size=batch_size, shuffle=True, num_workers=2, pin_memory=True)
    test_loader = torch.utils.data.DataLoader(test_set, batch_size=batch_size, shuffle=False, num_workers=2, pin_memory=True)
    return train_loader, test_loader


def train_one_epoch(model, loader, optimizer, criterion, lambda_sparse):
    model.train()
    running_loss = 0.0
    for images, labels in loader:
        images, labels = images.to(device), labels.to(device)
        optimizer.zero_grad()
        logits = model(images)
        total_loss = criterion(logits, labels) + lambda_sparse * model.sparsity_loss()
        total_loss.backward()
        nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
        optimizer.step()
        running_loss += total_loss.item()
    return running_loss / len(loader)


def evaluate(model, loader):
    model.eval()
    correct, total = 0, 0
    with torch.no_grad():
        for images, labels in loader:
            images, labels = images.to(device), labels.to(device)
            predicted = model(images).argmax(dim=1)
            correct += (predicted == labels).sum().item()
            total += labels.size(0)
    return 100.0 * correct / total


def run_experiment(lambda_sparse, train_loader, test_loader, num_epochs=60):
    print(f"\n{'='*50}\nRunning experiment  λ = {lambda_sparse}\n{'='*50}")
    model = SelfPruningNet().to(device)

    optimizer = optim.AdamW(model.parameters(), lr=1e-3, weight_decay=1e-4)
    scheduler = optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=num_epochs)
    criterion = nn.CrossEntropyLoss(label_smoothing=0.1)

    for epoch in range(1, num_epochs + 1):
        avg_loss = train_one_epoch(model, train_loader, optimizer, criterion, lambda_sparse)
        scheduler.step()
        if epoch % 10 == 0 or epoch == 1:
            acc = evaluate(model, test_loader)
            print(f"Epoch {epoch:02d}/{num_epochs} | Loss: {avg_loss:.4f} | Acc: {acc:.2f}% | Sparsity: {model.compute_sparsity():.1f}%")

    final_acc = evaluate(model, test_loader)
    final_sparsity = model.compute_sparsity()
    print(f"\nFinal → Accuracy: {final_acc:.2f}%  |  Sparsity: {final_sparsity:.1f}%")
    return {"lambda": lambda_sparse, "test_accuracy": final_acc, "sparsity": final_sparsity, "gate_values": model.get_all_gates()}


def plot_gate_distribution(result, save_path):
    fig, ax = plt.subplots(figsize=(9, 5))
    ax.hist(result["gate_values"], bins=80, color="#2563EB", edgecolor="white", linewidth=0.3)
    ax.set_title(f"Gate Value Distribution  (λ={result['lambda']})\nTest Accuracy: {result['test_accuracy']:.2f}%  |  Sparsity: {result['sparsity']:.1f}%", fontsize=13)
    ax.set_xlabel("Gate Value  (0 = pruned, 1 = fully active)", fontsize=11)
    ax.set_ylabel("Count", fontsize=11)
    ax.axvline(0.01, color="#EF4444", linestyle="--", linewidth=1.4, label="Prune threshold (0.01)")
    ax.legend(fontsize=10)
    plt.tight_layout()
    plt.savefig(save_path, dpi=150)
    plt.close()


def plot_all_gates_comparison(results, save_path):
    fig, axes = plt.subplots(1, 3, figsize=(16, 5), sharey=True)
    colors = ["#10B981", "#F59E0B", "#EF4444"]
    for ax, res, color in zip(axes, results, colors):
        ax.hist(res["gate_values"], bins=80, color=color, edgecolor="white", linewidth=0.3)
        ax.set_title(f"λ = {res['lambda']}\nAcc: {res['test_accuracy']:.1f}%  Sparsity: {res['sparsity']:.1f}%", fontsize=11)
        ax.set_xlabel("Gate Value")
        ax.axvline(0.01, color="black", linestyle="--", linewidth=1.2)
    axes[0].set_ylabel("Count")
    fig.suptitle("Gate Value Distributions for Different λ Values", fontsize=14)
    plt.tight_layout()
    plt.savefig(save_path, dpi=150)
    plt.close()


def main():
    BATCH_SIZE = 128
    NUM_EPOCHS = 60
    LAMBDAS = [1e-5, 1e-4, 1e-3]

    os.makedirs("outputs", exist_ok=True)
    train_loader, test_loader = get_cifar10_loaders(BATCH_SIZE)

    results = []
    for lam in LAMBDAS:
        results.append(run_experiment(lam, train_loader, test_loader, NUM_EPOCHS))

    print("\n" + "="*55)
    print(f"  {'Lambda':<12}  {'Test Accuracy':>15}  {'Sparsity Level':>16}")
    print("  " + "-"*51)
    for res in results:
        print(f"  {res['lambda']:<12}  {res['test_accuracy']:>14.2f}%  {res['sparsity']:>15.1f}%")
    print("="*55)

    plot_gate_distribution(results[1], "outputs/gate_distribution_best.png")
    plot_all_gates_comparison(results, "outputs/gate_distributions_comparison.png")
    print("\nDone. Plots saved to outputs/")


if __name__ == "__main__":
    main()